name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run formatting check
        run: npx prettier --check src/

      - name: Test Electron app startup
        run: |
          timeout 10s npm start || true
          echo "Electron app startup test completed"

  build:
    runs-on: ${{ matrix.os }}
    needs: lint-and-test

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build for platform
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            npm run build:mac
          elif [ "${{ runner.os }}" = "Linux" ]; then
            npm run build:linux
          elif [ "${{ runner.os }}" = "Windows" ]; then
            npm run build:win
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: dist/
